%
% Global pointer variables
%
global aih bjh cellmark markuface markvface outu_ij out_ij out_ip1j out_im1j out_ijp1 ...
    out_ijm1 outu_ip1j outu_im1j outv_ij outv_ijp1 outv_ijm1 in_ij ...
    in_ip1j in_ip1jm1 in_im1j in_ijp1 in_ijm1 inu_ij inu_ip1j inu_im1j inv_ij ...
    inv_ijp1 inv_ijm1 inu_ijm1 inu_ip1jm1 inv_ip1jm1 inv_ip1j ...
    inp_ij ipoly jpoly poly_ij edge_u_ij edge_u_ijm1 edge_v_ij edge_v_im1j ...
    advu_ij advu_ip1j advu_im1j advu_ijp1 advu_ijm1 ...
    advv_ij advv_ip1j advv_im1j advv_ijp1 advv_ijm1 ...
    bcu_ip1j bcu_im1j bcu_ijp1 bcu_ijm1 ... 
    bcv_ip1j bcv_im1j bcv_ijp1 bcv_ijm1 ...
    v_type3u u_type3u u_type3v v_type3v ...
    u_type3u_inner1 u_type3u_inner2 ...
    v_type3u_inner1 v_type3u_inner2 ...
    u_type3v_inner1 u_type3v_inner2 ...
    v_type3v_inner1 v_type3v_inner2 ...
    cellmark_dumbarton


    